name: chess
description: "a simple chess application"

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.6
  bishop: ^1.4.4
  google_sign_in: ^6.2.1
  gap: ^3.0.1
  google_fonts: ^6.2.1
  firebase_core: ^2.24.2
  dio: ^5.6.0
  logger: ^2.4.0
  json_annotation: ^4.9.0
  shared_preferences: ^2.2.2
  get_storage: ^2.1.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  json_serializable: ^6.7.1


flutter:
  uses-material-design: true

  assets:
    - assets/images/
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
